apiVersion: apps/v1
kind: Deployment
metadata:
  name: acrisure-deployment
  labels:
    app: acrisure-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: acrisure-deployment
          image: us.gcr.io/altway-internal/acrisure-nextjs
          imagePullPolicy: IfNotPresent