apiVersion: v1
kind: Service
metadata:
  name: acrisure-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: acrisure.internal.prod.acrisuretechnology.com.
    networking.gke.io/load-balancer-type: "Internal"