version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  deploy:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"		

# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main