version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"
# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - build
      - test:
          filters:
             branches:
               only:
                 - main
             tags:
               only: /^dev\d+\.\d+\.\d+$/
  build1:
    when:
      and: 
        - equal: [ "^[0-9a-zA-Z]+.ci-dev" , << pipeline.git.tag >> ]
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - build
      - test

