version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: echo << pipeline.git.tag >>
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"
# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - build
      - test:
          filters:
             branches:
               only:
                 - main
             tags:
               only: "/ci-dev.*/"
  build1:
    when:
      and: 
        - tag: "/ci-dev.*/"
        - equal: [ "dev5", << pipeline.git.branch >> ]
    jobs:
      - build
      - test

