apiVersion: apps/v1
kind: Deployment
metadata:
  name: acrisure-deployment
  labels:
    app: acrisure-deployment
spec:
  template:
    spec:
      containers:
        - name: acrisure-deployment
          image: us.gcr.io/altway-internal/acrisure-nextjs:dev
          env:
            - name: SITECORE_API_KEY
              value: null
              valueFrom:
                secretKeyRef:
                  name: sitecore-api-key
                  key: sitecore-api-key
            - name: PUBLIC_URL
              value: "https://acrisure-nextjs.altway.com"