apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: sitecore-api-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store-py
    kind: ClusterSecretStore
  target:
    name: sitecore-api-key
    creationPolicy: Owner
  dataFrom:
    - key: sitecore-api-key
      version: latest
      