apiVersion: v1
kind: Service
metadata:
  name: acrisure-service
  annotations:
    # external-dns.alpha.kubernetes.io/hostname: acrisure.internal.dev.acrisuretechnology.com
    # networking.gke.io/load-balancer-type: "Internal"
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: acrisure-deployment

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acrisure-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: acrisure-ingress-ip
  labels:
    app: acrisure
spec:
  defaultBackend:
    service:
      name: acrisure-service
      port:
        number: 3000
  tls:
  - secretName: altway-web-cert
 
# ---
# apiVersion: compute.cnrm.cloud.google.com/v1beta1
# kind: ComputeAddress
# metadata:
#   name: acrisure-ingress-ip
# spec:
#   location: global